[package]
name = "emigui-miniquad"
version = "0.1.0"
authors = ["Logachev Fedor <not.fl3@gmail.com >"]
edition = "2018"

[dependencies]
egui = "0.8.0"
miniquad = { version = "=0.3.0-alpha.26" }

[dev-dependencies]
egui_demo_lib = "0.8.1" # For example
